# Generated by Django 5.2.7 on 2025-11-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('IdUser', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
